# Generated by Django 3.2.4 on 2021-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Contacto')),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=254)),
                ('Asunto', models.CharField(max_length=50)),
                ('Mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('idRegistro', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de registro')),
                ('Usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo del usuario')),
                ('Numero', models.IntegerField(unique=True, verbose_name='Numero de telefono')),
            ],
        ),
    ]
